OPERATIONS = {
    "A": ("Anchor", "Bind execution to a protected reference."),
    "B": ("Bridge", "Connect semantic regions without forced merge."),
    "C": ("Cycle", "Advance a bounded recursive cycle."),
    "D": ("Drift", "Mark divergence from an anchor or invariant."),
    "E": ("Evidence", "Bind recoverable support to active state."),
    "F": ("Fold", "Commit state, failures, and lineage to memory."),
    "G": ("Guard", "Check authority, affected parties, gates, boundaries, and effects."),
    "H": ("Horizon", "Bind execution to a consequence horizon."),
    "I": ("Invariant", "Lock protected commitments."),
    "J": ("Junction", "Preserve branch intersection without collapse."),
    "K": ("Kernel", "Initialise the semantic kernel."),
    "L": ("Limit", "Apply an execution limit."),
    "M": ("Merge", "Merge only when protected fields remain compatible."),
    "N": ("Novelty", "Mark newly introduced semantic content."),
    "O": ("Observe", "Record source condition without interpretation loss."),
    "P": ("Prove", "Evaluate support under evidence and unknowns."),
    "Q": ("Query", "Generate questions from unresolved unknowns."),
    "R": ("Resolve", "Resolve unknowns only through declared evidence."),
    "S": ("State", "Create an immutable semantic snapshot."),
    "T": ("Transition", "Advance an authorised state transition."),
    "U": ("Unknown", "Activate typed unresolved information."),
    "V": ("VectorInvert", "Construct another route preserving intent and invariants."),
    "W": ("Weave", "Compose positions while preserving dissent."),
    "X": ("Exchange", "Execute declared value movement visibly."),
    "Y": ("Yield", "Produce a bounded output."),
    "Z": ("CompressExpand", "Compress only when recovery is safe; otherwise expand."),
}
PUBLIC_CORE = frozenset("OEUIGVFYZ")
SEALS = {
    "Correction": ("D", "A", "F", "P", "Y"),
    "Frontier": ("O", "S", "N", "E", "G", "I", "U", "Q"),
    "Sovereignty": ("G", "I", "V", "P", "Y"),
    "Cascade": ("E", "N", "J", "C", "F", "P", "Y"),
    "ProtectedDissent": ("W", "U", "G", "V", "Y"),
}
