from __future__ import annotations

from typing import Any, Protocol


class LamagueAdapter(Protocol):
    name: str
    version: str

    def supports_atom(self, atom: str) -> bool: ...
    def map_atom(self, atom: str) -> Any: ...
    def map_operator(self, operator: str, operands: list[Any]) -> Any: ...
    def validate_invariant(self, name: str, expression: Any) -> dict: ...
    def validate_requirement(self, expression: Any) -> dict: ...
    def validate_prohibition(self, expression: Any) -> dict: ...
